services:
  app:
    build: .
    container_name: dbmeta-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sampledb
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: dev1234
      JASYPT_ENCRYPTOR_PASSWORD: my-secret-key-1234
    depends_on:
      - postgres
      - mariadb

  postgres:
    image: postgres:16
    container_name: dbmeta-postgres
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mariadb:
    image: mariadb:11
    container_name: dbmeta-mariadb
    environment:
      MARIADB_DATABASE: sampledb
      MARIADB_USER: dev
      MARIADB_PASSWORD: dev1234
      MARIADB_ROOT_PASSWORD: root1234
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  postgres_data:
  mariadb_data:
